kind: PersistentVolume
apiVersion: v1
metadata:
  name: smartquaildb-pv-volume
  namespace: postgres
  labels:
    type: local
    app: smartquaildb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smartquaildb-pv-claim
  namespace: postgres
  labels:
    app: smartquaildb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi