apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
  labels:
    app: smartquaildb
data:
  POSTGRES_PASSWORD: "c21hcnRxdWFpbGRldjE3MTlwYXNz" 
  POSTGRES_DB: "UU5PREUwMV9ERVZfREI="
  POSTGRES_HOST: "c21hcnRxdWFpbGRi"
  POSTGRES_PORT: "NTQzMg=="
  POSTGRES_READY: "MQ=="
  POSTGRES_USER: "c3FhZG1pbmRi"
